name: Run Kubeflow Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - qa

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile the Pipeline
        run: |
          python pipeline/mlops_pipeline.py

      - name: Upload Pipeline YAML
        uses: actions/upload-artifact@v3
        with:
          name: mlops-pipeline
          path: pipeline/mlops_pipeline.yaml
          
      - name: Run Kubeflow Pipeline
        run: |
          export KUBEFLOW_PIPELINE_HOST="http://your-kubeflow-server"
          kfp --endpoint=$KUBEFLOW_PIPELINE_HOST pipeline upload -p "MLOps Pipeline" pipeline/mlops_pipeline.yaml
        env:
          KUBEFLOW_USERNAME: ${{ secrets.KUBEFLOW_USERNAME }}
          KUBEFLOW_PASSWORD: ${{ secrets.KUBEFLOW_PASSWORD }}
